spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/bookshopdb
    username: bookmaster
    password: 1111
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081